[package]
name = "surrealdb-simple-migration"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "surrealdb-simple-migration"
path = "src/main.rs"

[dependencies]
serde = "1.0.203"
surrealdb = "1.5.1"
tokio = { version = "1.37.0", features = ["full"] }
